---
abstract: 'website support for L<EntityModel>'
author:
  - 'Tom Molesworth <cpan@entitymodel.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: EntityModel-Web
requires:
  EntityModel: 0.017
  HTTP::Date: 0
  URI: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=EntityModel-Web
  homepage: http://search.cpan.org/dist/EntityModel-Web/
version: 0.004
