---
abstract: 'website support for L<EntityModel>'
author:
  - 'Tom Molesworth <cpan@entitymodel.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300000, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: EntityModel-Web
requires:
  EntityModel: 0.010
  EntityModel::Class: 0.007
  HTTP::Date: 0
  URI: 0
version: 0.003
